[template]
src   = "ca.crt.tmpl"
dest  = "/usr/local/etc/ssl/private/ca.crt"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "/global/tls/ca_cert",
]
reload_cmd = "/usr/sbin/service nginx reload"
