[template]
keys = [
  "nginx_proxy",
  "nginx_www_redirect_domains"
]
mode = "0644"
src = "nginx-proxy.tmpl"
dest = "/etc/nginx/nginx.conf"
check_cmd  = "/usr/sbin/nginx -t -c {{ .src }}"
reload_cmd = "/usr/sbin/nginx -s reload"
