[template]
keys = [
  "nginx_proxy",
  "nginx_www_redirect_domains"
]
owner = "nginx"
mode = "0644"
src = "nginx-proxy.tmpl"
dest = "/etc/nginx/nginx.conf"
check_cmd  = "mkdir -p /tmp/confd/nginx/{{ .src }} && cp {{ .src }} /tmp/confd/nginx/{{ .src }}/nginx.conf && /usr/sbin/nginx -t -c {{ .src }}"
reload_cmd = "/usr/sbin/nginx -s reload"
