[template]
src   = "tls.key.tmpl"
dest  = "/usr/local/etc/ssl/private/tls.key"
owner = "root"
group = "root"
mode  = "0600"
keys = [
  "/global/tls/key",
]
reload_cmd = "/usr/sbin/service nginx reload"
