[template]
src   = "tls.crt.tmpl"
dest  = "/usr/local/etc/ssl/private/tls.crt"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "/global/tls/cert",
]
reload_cmd = "/usr/sbin/service nginx reload"
