#!/bin/sh

until confd -onetime -node http://$ETCD_PORT_4001_TCP_ADDR:$ETCD_PORT_4001_TCP_PORT -config-file /etc/confd/confd.toml; do
  echo "[confd] waiting for confd to refresh config files"
  sleep 5
done

exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
