[template]
keys = [
  "/"
]
mode = "0644"
src = "nginx-proxy.tmpl"
dest = "/etc/nginx/nginx.conf"
check_cmd  = "cp {{ .src }} /tmp/nginx.conf && /usr/sbin/nginx -t -c {{ .src }}"
reload_cmd = "/usr/sbin/nginx -s reload"
